language: R
cache:
  packages: true
before_install:
- mkdir -p ~/.R/gargle
- openssl aes-256-cbc -K $encrypted_d4a97966b6bb_key -iv $encrypted_d4a97966b6bb_iv
  -in all-keys-needed.tar.enc -out ~/.R/gargle/all-keys-needed.tar -d
- tar xvf ~/.R/all-keys-needed.tar
script:
- Rscript -e 'source("R/daily-job_get-meetup-events_save-to-gdrive.R")'
