language: R
cache:
  packages: true
before_install:
- openssl aes-256-cbc -K $encrypted_d4a97966b6bb_key -iv $encrypted_d4a97966b6bb_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- Rscript -e 'source("R/daily-job_get-meetup-events_save-to-gdrive.R")'
